# Generated by Django 3.2.9 on 2021-11-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0002_remove_defect_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Defect',
        ),
    ]
